### PR TITLE
Add basic style linting

### PR DESCRIPTION
**Pull request by bbannier**
Triggered by https://github.com/zeek/packages/pull/215#pullrequestreview-1595361129, this adds a pre-commit setup and matching GH action which performs very basic, stylistic linting (sorting of `zkg.index` files, whitespace issues).

For the GH action part, I was actually wondering whether to use the action from https://pre-commit.ci/ instead of running pre-commit manually. My expectation would be that the way it can leave review comments might be more approachable than simply failing CI. It does however require adding action permissions to the repo which I didn't want to do on a whim.

### CODE REVIEW

**Review by awelzel — APPROVED** [review]
:tada: - thanks Benjamin for just doing it.

**Comment by ckreibich** [comment]
Minor nit: case-insensitive sorting would arguably be better — note how the [CVE packages in the Corelight space](https://github.com/zeek/packages/blob/master/corelight/zkg.index#L1-L20) got pulled apart now.

**Comment by bbannier** [comment]
> Minor nit: case-insensitive sorting would arguably be better — note how the [CVE packages in the Corelight space](https://github.com/zeek/packages/blob/master/corelight/zkg.index#L1-L20) got pulled apart now.

I opened #218 to use case-insensitive sorting.

**Comment by awelzel** [comment]
> note how the [CVE packages in the Corelight space](https://github.com/zeek/packages/blob/master/corelight/zkg.index#L1-L20) got pulled apart now.

Consistent naming unfortunately cannot be enforced on a linter level :-)

**Comment by bbannier** [comment]
> > note how the [CVE packages in the Corelight space](https://github.com/zeek/packages/blob/master/corelight/zkg.index#L1-L20) got pulled apart now.
> 
> Consistent naming unfortunately cannot be enforced on a linter level :-)

My PR had nothing to do with linting package names.

That being said, one could certainly make a case for linting them. Right now an index just contains a list of repositories and doesn't even encode what packages are exported from them. This makes it pretty easy to e.g., accidentally create package names which are too similar and we have no way to catch that before we do a fresh aggregation. If our package source was bigger and more busy one might be worried about this design as it would be possible to typosquad more popular packages (in particular with `zkg` allowing to drop the org name for convenience). Some forms of typosquadding could be detected automatically, but that wouldn't help user installing a just updated, not yet aggregate package.

**Comment by ckreibich** [comment]
> an index [...] doesn't even encode what packages are exported from them

What do you mean here, Benjamin? I'd argue it does, since each URL is one package and also implies its name.

I would generally mostly leave this space alone. What we have is pretty simple and works, and there's a lot else about `zkg` to improve. The main downside of two packages being called "foo" is that you can no longer install "foo", you have to prefix it with at least the user name in the index (much like in NPM, say, with its scoped vs unscoped names — I actually think what we have is better!). You won't suddenly install an unintended package of the same name, which I certainly agree would be a no-go.

I could see naming info as part of "assistive" linting we've discussed in the past when somebody submits a package (like whether the package has a license, etc) — something like "Most similarly named packages: X, Y, Z".

**Comment by bbannier** [comment]
> > an index [...] doesn't even encode what packages are exported from them
> 
> What do you mean here, Benjamin? I'd argue it does, since each URL is one package and also implies its name.

You are right, I had thought we had a metadata field for the package name, but we don't (maybe confused this with `description`).

Like I said, I didn't plan to do anything for enforcing package naming conventions since it is both tricky and likely disruptive.

**Pull request merged**
