### PR TITLE
Aggregate-push metadata periodically and when we push to master

### PR DESCRIPTION
**Pull request by ckreibich**
This runs "zkg -vvv refresh --aggregate --push" to update the aggregate.meta file. (As of zkg 2.10.0 the "-vvv" shows which packages changed and whether a commit actually happened.)

You can see an example of a run in my fork: https://github.com/ckreibich/packages/runs/2899041571?check_suite_focus=true

I made up a name and email address for the author of the commits ... let me know if we have anything more suitable.

### CODE REVIEW

**Comment by 0xxon** [comment]
This is great :)

Can we get this to... warn us in some ways in case zkg reports errors?

**Comment by ckreibich** [comment]
Yep ... it just depends on what kinds of errors you mean. `zkg` currently distinguishes two kinds during metadata aggregation: "hard" problems if it can't clone/pull the a package source, and "soft" ones when there are errors while cranking through the packages. The former make it `exit(1)`, which will fail the CI run and trigger a notification. The latter currently don't make it error — it writes out a warning and the aggregate is still pushed without the offending packages.

I could see adding a new flag so that the processing logic remains unchanged, but we exit (say `exit(2)`) when any packages caused trouble. What do you think?

**Comment by ckreibich** [comment]
@0xxon I'm currently planning to get the above into zkg, wrap up a new release (to be shipped with Zeek 4.1), and then switch the invocation to using the new flag to CI errors out when there are any package metadata problems.

**Comment by 0xxon** [comment]
Sounds good.

**Pull request merged**
