### PR TITLE
Add a Zeek Package that extracts some features from file.pcap

### PR DESCRIPTION
**Pull request by ManuTheKing**
Zeek Package that extends the functionality of Zeek network analysis framework. This package automatically recognizes IRC communication in a packet capture (pcap) file and automatically extract features from it. The goal for the feature extraction is to describe an individual IRC communications that occur in the pcap file as accurately as possible.
This is a work for an exam of University of Bologna.

### CODE REVIEW

**Review by bbannier — CHANGES_REQUESTED** [review]
Thanks for adding your package to the package index @ManuTheKing!

I left only minor comments below.

**Comment by ManuTheKing** [comment]
I have remove the .DS_Store file

**Comment by bbannier** [comment]
Merged with bbb4fc5f5d8be53b5a3e25463dd710d690b2bc06.

**Comment by ManuTheKing** [comment]
Sorry, one question: How I can install my package on terminal? For example: zig install zeek/path_my_package, but not install anything. Thank you

**Comment by bbannier** [comment]
> How I can install my package on terminal? For example: zig install zeek/path_my_package, but not install anything.

```console
# Refresh package index.
$ zkg refresh

# Install package. This does not install unless prompted.
$ zkg install Zeek-Pcap-Features-Extractor
The following packages will be INSTALLED:
  zeek/cyberUniBO/Zeek-Pcap-Features-Extractor (main)

Proceed? [Y/n]
```

**Comment by ManuTheKing** [comment]
Thank you for your disponibility! Now it's possible install all. Thank you so much

**Pull request closed without merging**
