### PR TITLE
Clean up bro-pkg.index files

### PR DESCRIPTION
**Pull request by ckreibich**
No functional difference here, but nowadays these files should be called `zkg.index`, and the Corelight space actually had both.

### CODE REVIEW

**Comment by 0xxon** [comment]
So - you are in principle right that we should do this - and I, so far, simultaneously have been afraid to do this change (I thought about it in the past).

From my understanding, performing this will instantly render anyone who still is using bro-pkg (so an old version) unable to use the package repository. Which is why, so far, I just have defaulted to leave stuff in the bro-pkg.index files. We can decide that that is ok - but we probably should discuss it :)

**Comment by 0xxon** [comment]
Also - I am sorry I missed this so long.

**Comment by rsmmr** [comment]
I'd be fine moving pretty quickly on this, along with the 4.1 release sounds good to me if we announce it now. Upgrading to a recent zkg really doesn't look like much of an issue: it comes with 4 anyways, and through `pip` it's a simple update that won't break anything (afaik).

**Comment by ckreibich** [comment]
I've refreshed this, now that 4.1 is out. We did mention the planned transition a while back, so I think we're good to go.

**Review by 0xxon — APPROVED** [review]
sounds good.

**Pull request merged**
